# 홈 설정
title: han's
email: lokiju1234@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  Themed by ejjoo
github_username: ejjoo
highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/
timezone: Asia/Seoul
