# 홈 설정
title: HangWoo
email: lokiju1234@naver.com
description: 재미로 하는 블로그
github_username: lokiju12
highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/
timezone: Asia/Seoul
